name: Deploy for Azure

on:
  workflow_call:
    secrets:
      credentials:
        description: "credentials"
        required: true
    inputs:
      target-env:
        description: "Target Environment"
        required: true
        type: string

steps:
  - name: Check Out Repo
    uses: actions/checkout@v3

  - name: Login to Azure
    uses: azure/login@v1
    with:
      creds: ${{ secrets.credentials }}

  - name: Set up Docker Buildx
    uses: docker/setup-buildx-action@v1

  - name: Cache Docker layers
    uses: actions/cache@v2
    with:
      path: /tmp/.buildx-cache
      key: ${{ runner.os }}-buildx-${{ github.sha }}
      restore-keys: |
        ${{ runner.os }}-buildx-


  - name: Docker Auth
    id: docker-auth
    uses: docker/login-action@v1
    with:
      username: ${{ secrets.AZURE_REGISTRY_USERNAME }}
      password: ${{ steps.auth.outputs.access_token }}
      registry: feature.azurecr.io

#  - name: Build and deploy Container App
#    uses: azure/container-apps-deploy-action@v1
#    with:
#      acrName: myregistry
#      containerAppName: my-container-app
#      resourceGroup: my-rg
#      imageToDeploy: myregistry.azurecr.io/app:${{ github.sha }}
