name: Deploy for Azure

on:
  push:
    branches:
      - 'feature/add-azure-ci'

env:
  SERVICE_NAME: go-cicd

jobs:
  login:
    runs-on: ubuntu-latest
    permissions:
      # OIDC 接続を実行するために必要
      id-token: write

    steps:
      - name: Check Out Repo
        uses: actions/checkout@v3

      - name: Login in to Azure
        id: auth
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          token_format: access_token

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Docker Auth
        id: docker-auth
        uses: docker/login-action@v1
        with:
          username: oauth2accesstoken
          password: ${{ steps.auth.outputs.access_token }}
          registry: feature.azurecr.io

      - name: Build and Push Docker image
        uses: docker/build-push-action@v3
        with:
          context: ./
          file: ./docker/prod/Dockerfile
          push: true
          tags: feature/${{ env.SERVICE_NAME }}/develop:${{ github.sha }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache

