name: CI

on: [pull_request]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Go 1.21
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
          cache: false

#      - name: Check typos
#        uses: crate-ci/typos@v1.0.4
#        with:
#          files: ./
#          config: ./_typos.toml

      - name: mod download
        run: go mod download

      - name: build
        run: make build

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go 1.21
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          args: --timeout 100s
          skip-pkg-cache: true
          skip-build-cache: true
