name: Deploy for GCP

on:
  push:
    branches:
      - 'feature/gcp-terraform'

jobs:
  start-deploy:
    permissions:
      id-token: write
      contents: read
    uses: ./.github/workflows/_gcp_deploy.yml
    secrets:
      gcp-project-id: ${{ secrets.GCP_PROJECT_ID }}
      gcp-project-number: ${{ secrets.GCP_PROJECT_NUMBER }}
    with:
      target-env: dev
